# Laboratoire 6 – Effet photoélectrique {-}

## Consignes {-}

Chaque équipe doit remettre :
  - un rapport complet papier, broché, qui inclut tous les éléments décrits
    plus bas dans l'ordre;
  - un fichier Excel contenant tous les calculs nécessaires effectués à l'aide
    de formules appropriées. Assurez-vous que votre fichier Excel calcule la
    constante de Planck, le travail d'extraction et la fréquence seuil. Le
    fichier Excel doit être remis sur Léa.

La date limite de remise est le mardi 8 mai 2018 à 17h.

Je corrigerai le fichier Excel en remplaçant vos données par les miennes. Les
valeurs finales calculées dans votre fichier devront être correctes.

Vous n'avez pas le droit d'utiliser de listes à puces ou à numéros. Vous
devez répondre aux exigences en rédigeant un texte continu. Toutes vos
phrases doivent compter un maximum de 15 mots.  Votre rapport de laboratoire
doit compter un maximum de 4 pages, incluant les tableaux et le graphique.
Je ne corrigerai pas les phrases plus longues que 15 mots, ni les pages
au-delà de la quatrième.

Votre rapport de laboratoire doit inclure les sections suivantes, dans
l'ordre. 

## Introduction {-}

L'objectif de cette section est de présenter le modèle théorique que vous
voulez vérifier expérimentalement de même que la méthode d'analyse que vous
utiliserez.

Présentez la formule de l'effet photoélectrique (équation 4 du guide de
laboratoire) en prenant soin de bien définir chacun des symboles qui y
apparait. Expliquez quelles quantités seront mesurées directement au
laboratoire et quelles sont les deux constantes dont vous voulez déterminer
la valeur.

Expliquez comment vous linéarisez l'équation de l'effet photoélectrique.
Quelles sont les quantités qui jouent le rôle de variable indépendante et
dépendante?  Quelle est l'allure du graphique attendue? Quelles sont les
valeurs attendues des paramètres de la droite de régression?

## Résultats {-}

Présentez vos données mesurées directement dans deux tableaux. Le premier
contient les valeurs de potentiel d'arrêt pour différentes longueurs d'ondes.
Incluez aussi dans ce tableau les valeurs correspondantes de fréquence.  Le
second tableau contient les valeurs de potentiel d'arrêt pour différentes
tailles d'ouverture.

Vous n'avez pas à justifier les incertitudes.

Présentez un graphique de votre modèle linéarisé incluant les droites
extrêmes. Ce graphique doit occuper un minimum d'une demi-page.

## Conclusion {-}

À partir de vos résultats, expliquez si l'équation de l'effet photoélectrique
est vérifiée. Vos explications doivent inclure une comparaison de la
constante de Planck mesurée à la valeur théorique. Commentez également sur la
valeur expérimentale du travail d'extraction et de la fréquence seuil.

Discutez de l'influence de la puissance lumineuse sur le potentiel d'arrêt.
Comment la puissance lumineuse a-t-elle variée dans vos manipulations? Quelle
est l'incidence observée sur le potentiel d'arrêt? Est-ce conforme à ce que
la théorie prédit?

Si vos modèles ne sont pas vérifiés, expliquez les sources probables
du problème.
